.TH SHKD 1 shkd
.SH NAME
Simple HotKey Daemon.
.SH SYNOPSIS
.SY shkd
.RI [ OPTIONS ] " INPUT_DEVICE" " ..."
.YS
.SH DESCRIPTION
.PP
shkd is a simple hotkey daemon for the Linux console.
.SH OPTIONS
.TP
.BI -h
Show the synopsis and quit.
.TP
.BI -v
Show the version and quit.
.TP
.BI -t
Output the name and the keycode of the incoming key press events (press 'esc' to quit).
.TP
.BI -c " CONFIG_FILE"
Read configuration from the given file instead of the default (/etc/shkdrc).
.SH CONFIGURATION FILE FORMAT
.PP
Each line of the configuration file is interpreted as so:
.IP \(bu 2
If it starts with
.IR # ,
it is ignored.
.IP \(bu 2
If it starts with one or more white space characters (as defined by 
.BR isspace " (3))"
it is read as a command.
.IP \(bu 2
Otherwise, it is parsed as a hotkey: each key name is separated by spaces or
.IR +
characters.
.SS Example:
.EX
brightnessup
    foo +1
volumedown
    bar -1
meta + alt + shift + ctrl + zenkakuhankaku
    baz --quux /foo/bar
.EE
.SH AUTHOR
.MT nihilhill@gmail.com
Bastien Dejean
.ME
.SH LINKS
.UR https://github.com/baskerville/shkd
Homepage
.UE
